version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: my-mysql-db
    ports:
      - '3306:3306'
    volumes:
      - ./dockerCompose/mysql:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 123456789
      MONGO_INITDB_DATABASE: my-mongo-db
    ports:
      - '27017:27017'
    volumes:
      - ./dockerCompose/mongodb:/data/db
