###
### API dice game
###

# Create new player
POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "name": "Homer Simpson"
}

# Rename player:
PUT http://localhost:3000/players/1
content-type: application/json

{
  "name": "Bart Simpson" 
}

# Get all players and their success rates
GET http://localhost:3000/players


# -----------------------------------------

# Obtener un jugador específico por su ID
GET http://localhost:3000/players/123

# Eliminar un jugador existente por su ID
DELETE http://localhost:3000/players/123

# Obtener todas las tiradas de un jugador específico por su ID
GET http://localhost:3000/players/123/throws

# Registrar una nueva tirada para un jugador específico por su ID
POST http://localhost:3000/players/123/throws
content-type: application/json

{
  "dice1": 4,
  "dice2": 3,
  "winner": true
}
